### ISSUE TITLE
CloudTrail is not yet enabled

### ISSUE THREAD

**Issue by tinnightcap** [Nubisproject/nubis-stacks#127]
Currently IT is waiting on OpSec for delivery of the secure cloudtrail storage configuration. Without this audit logs of actions taken in the nubis AWS accounts will not be created and protected.

Recommendations :

Complete the secure cloudtrail storage system and deploy into all nubis AWS accounts

**Comment by gozer** [comment]
@limed, this is all done, right ?

**Comment by limed** [comment]
Yes all done here see https://github.com/nubisproject/nubis-cloudtrail for code reference
