### ISSUE TITLE
[s3] Enable encrypted uploads

### ISSUE THREAD

**Issue by limed** [Nubisproject/nubis-stacks#153]
Enable encrypted uploads, http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

**Comment by gozer** [comment]
The big problem/challenge is that CloudFormation doesn't expose this...

**Comment by limed** [comment]
Can't we use bucket policy for this? Or is the link that I posted not the same thing as what you are thinking about?

**Comment by gozer** [comment]
This is a policy to ensure non-encrypted content isn't uploaded to the bucket, it doesn't do transparent encryption itself

**Comment by gozer** [comment]
I thought server-side encryption was a bucket proprety, but from reading some more, it smells like it's something the s3 client can request, so pairing that with the policy you are pointing at might be the solution...
