### ISSUE TITLE
[IAM] Amazon only allows one role per instance-profile, which is bad for us.

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-stacks#161]
We need to stop using Roles out of S3 and into EC2, and instead go to using
Policies, of which 10 can be used to make up a role.

In short, things that create resources create AWS::IAM::Policy entites that
defines access to them.

Then for comsumers, like ec2-template, we pass in an array of policies and
let the stack generate both the role and the instance profile with them.

**Comment by gozer** [comment]
This means #101 is incomplete

**Comment by limed** [comment]
We need to do this for `eip.template` as well

**Comment by gozer** [comment]
Filed #163 to track this for eip.template
