### ISSUE TITLE
[RDS] Snapshot on delete

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-stacks#194]
From http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html:

"DeletionPolicy" : "Snapshot"

**Comment by limed** [comment]
Just want to point this out

``` bash
limed@river (master=):~/nubis/nubis-stacks$ git grep DeletionPolicy
rds-mysql.template:      "DeletionPolicy": "Snapshot"
rds-postgres.template:      "DeletionPolicy": "Snapshot"
```

**Comment by limed** [comment]
We're good to go folks, although it would be good to make that option an RDS parameter and default it to "Snapshot" but its not in scope for this issue
