### ISSUE TITLE
[bug] upload_to_s3 script fails to validate template

### ISSUE THREAD

**Issue by limed** [Nubisproject/nubis-stacks#253]
`upload_to_s3` script fails to validate a template because we don't specify a region even though validating a template has nothing to do with regions! At all!

``` bash
+ echo -n 'Validating ec2.template: '
Validating ec2.template: + export AWS_REGION=us-west-2
+ AWS_REGION=us-west-2
+ aws cloudformation --profile nubis-market validate-template --template-body file://ec2.template
You must specify a region. You can also configure your region by running "aws configure".
```

**Comment by gozer** [comment]
AWS_DEFAULT_REGION is the required variable.

And yes, it's silly, but validation happens server-side at AWS, so it needs to be specified, however silly that sounds
