### ISSUE TITLE
[RDS] Add support for read-replicas

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-stacks#60]
Message-ID: &lt;CAK6AZGJ4GL7x_c2_e1zEMzQwxZvhwCdaSOcar8NjRwcDa3SATA@mail.gmail.com&gt;

As we discussed in our meeting with Sheeri, we will have a future need to
support RDS read replicas in Nubis. While none of the projects we have in
queue directly points to requiring read replicas, we may discover we need
this in order to give Bugzilla the performance and scalability it needs.
We won't know this until we start testing. I will keep you both in the loop.

**Comment by tinnightcap** [comment]
Add read replicas in the same VPC. The number of replicas should be a parameter (zero to disable). This needs to integrate with consul (all replicas publish themselves as services in consul).

**Comment by tinnightcap** [comment]
Binlogging needs to be enabled for 24 hours. Need to be sure any deployments have enough disk space to accommodate this. This should be a parameter.
