### ISSUE TITLE
[ec2] Enable ssh access to instances

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-stacks#62]
Assuming this is something we want to do/allow, the question is how could it be implemented in a way that compromises the design principles as little as possible.
- [ ] How does ssh access itself get connected to ?
- [ ] How does authentication work ?
- [ ] How does permissions/privileges work (sudo/etc) ?
- [ ] How does auditing work ?
- [ ] How can we ensure tampered instances are not put back in rotation ?

My current thinking revolves around the idea of detaching an instance from the autoscaling group / ELB pool and direct the ssh user to that. It's a production instance for all intents and purposes but doesn't see live traffic anymore. Run your DB migrations from there, then kill the instance once you are done with it.

Needs more thinking, obviously.

https://svn.apache.org/repos/infra/infrastructure/trunk/projects/ckl/
http://linux.die.net/man/1/sudosh

**Comment by tinnightcap** [comment]
This is not something we are going to implement at this time.
