### ISSUE TITLE
[EIP] Allow self-assigned IP allocation

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-stacks#75]
We need to take the EIP self-allocation feature out of the jumphost and move it into a feature of the stacks

**Comment by limed** [comment]
Note that this works in conjunction with https://github.com/limed/nubis-puppet-eip

**Comment by gozer** [comment]
Oh, awesome! I didn't see that and it would probably make sense ot include a sample of that in the stack's README, for completenes.

We'll need to give a good look at that module and include it in nubis-base.

@limed, why don't you go ahead and file an issue in nubis-base for inclusion.

You'll need a release tag for it, but wait until completing review on that.

**Comment by limed** [comment]
I believe this issue has been resolved with the merge of PR #81 and also nubisproject/nubis-base#165
