### ISSUE TITLE
[ec2] Inbound SSH is allowed on all instances from the internet

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-stacks#96]
From https://mana.mozilla.org/wiki/display/SECURITY/Nubis#Nubis-#inboundsshopen

Inbound SSH is allowed on all instances from the internet

The nubis ec2 template allows inbound traffic on port 22 from all IPs instead of from the security group of the bastion hosts. This means that if an EIP is unintentionally applied to a host or a host is created in the public subnet, that host is accessible over ssh to all on the internet.

```
https://github.com/Nubisproject/nubis-stacks/blob/cde5aa4ed0b2a35aff28ad194b1a03fe163dc899/ec2.template#L186-L192
```

Recommendations :

Change the security group to only allow an origin value of a security group that contains the bastion hosts

**Comment by tinnightcap** [comment]
create security group in VPC, then attach both jumphosts and EC2 instances to it using lambda outputs

**Comment by gdestuynder** [comment]
see https://github.com/Nubisproject/nubis-stacks/pull/165/files#r40368282

**Comment by gdestuynder** [comment]
@marianpiper remedied
